# Generated by Django 2.2.1 on 2019-05-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('effectif_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preprint',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('publication_date', models.DateField()),
                ('description', models.TextField()),
                ('Subjects', models.ManyToManyField(blank=True, to='home.Subject')),
                ('tags', models.ManyToManyField(blank=True, to='home.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=20)),
                ('registration_date', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('nombre_prep', models.IntegerField()),
                ('preprints', models.ManyToManyField(blank=True, to='home.Preprint')),
                ('relation_authors', models.ManyToManyField(blank=True, related_name='_author_relation_authors_+', to='home.Author')),
            ],
        ),
    ]
